### ISSUE TITLE
getRecord() should auto-parse JSON

### ISSUE THREAD

**Issue by jancurn** [Apifier/apify-client-js#21]
`getRecord()` should automatically parse body if it has JSON content type. The resulting values should look like:
```javascript
{
  body: Object, // Parsed JSON object, or null (for unsupported content type or )
  rawBody: String, // or Buffer
  contentType: String
}
```
Use type-is library and `*/json` matcher for content type.

**Comment by mtrunkat** [comment]
Already done. We ommited rawBody since user can disable bodyParser.
