### ISSUE TITLE
Binary data returned as String from keyValueStores.getRecord()

### ISSUE THREAD

**Issue by jancurn** [Apifier/apify-client-js#27]
When I save binary data (a PNG image) using `keyValueStores.putRecord()` and then read it back using `keyValueStores.getRecord()`, the data is returned as String rather than Buffer. 

I'm using the following code in my act:

```javascript
await Apify.setValue('OUTPUT', buffer, { contentType: 'image/png' });
const val = await Apify.getValue('OUTPUT'); // returns string!
```

IMHO `getRecord()` should only convert to string if the data has the `text/*` content type, convert to JS object for the `application/json` content type, and for all other content types it should return raw Buffer. And if you specify `useRawBody: true` option, then it should return Buffer for everything.

**Comment by mtrunkat** [comment]
Fixed here: https://github.com/Apifier/apify-runtime-js/pull/6
